In [2]:
import numpy as np

## Datatypes & Attributes

In [5]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2.6,3.4],
               [4,3,51]])
a3 = np.array([[[1,2,3],
              [5,8,5]],
              [[5,7,3],
              [6,5,2]]])
a3

array([[[1, 2, 3],
        [5, 8, 5]],

       [[5, 7, 3],
        [6, 5, 2]]])

In [7]:
a2.shape

(2, 3)

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
a1.size, a2.size, a3.size #quantity of elements

(3, 6, 12)

In [11]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1     2
0  1.0  2.6   3.4
1  4.0  3.0  51.0

## Creating arrays

In [13]:
sample_array = np.array([1, 2 , 3])
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 4, 5, 8, 7],
       [2, 0, 4, 3, 8],
       [0, 6, 6, 1, 8]])

In [20]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.24899119, 0.6630111 , 0.64956692],
       [0.90497326, 0.81779596, 0.32005238],
       [0.06945738, 0.49694228, 0.41615543],
       [0.08553741, 0.06870203, 0.20794694],
       [0.62118854, 0.74809589, 0.99368409]])

In [21]:
random_array_2.shape

(5, 3)

In [ ]:
# Pseudo-random numbers
np.random.seed()